# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build
      run: echo 'hello world'
      
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy
      run: echo 'hello world'

