# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DAY_OF_WEEK: Asdf
  LINUX_VERSION: ubuntu-latest

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build
      run: export DAY_OF_WEEK="qwertz"
      
  deploy:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    needs: build
    environment: test
    steps:

    - name: Deploy ${{ env.c }}
 
      run: echo ${{ env.DAY_OF_WEEK }}

